"""Event Type Enum"""
from enum import Enum

class EventType(Enum):
    
    UPVOTE_QUESTION="UPVOTE_QUESTION"
    UPVOTE_ANSWER="UPVOTE_ANSWER"
    DOWNVOTE_QUESTION="DOWNVOTE_QUESTION"
    DOWNVOTE_ANSWER="DOWNVOTE_ANSWER"
    ACCEPT_ANSWER="ACCEPT_ANSWER"